"use client";
import { useActionState } from "react";
import { updateProjectAction, type ProjectActionState } from "../actions";
import { healthValues, lifecyclePhases, projectStatuses } from "../types";
import { FieldError } from "@/features/auth/components/field-error";
import { SubmitButton } from "@/features/auth/components/submit-button";

type Values = Record<string, string>;
const input = "min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-base text-slate-950 outline-none focus:border-slate-700 focus:ring-2 focus:ring-slate-300";
const textFields = [["name","Project name",200,false],["description","Project description",4000,true],["businessObjective","Business objective",4000,true],["sponsorName","Sponsor name",200,false]] as const;
const healthFields = [["overallHealth","Overall"],["scopeHealth","Scope"],["scheduleHealth","Schedule"],["budgetHealth","Budget"],["resourceHealth","Resource"],["riskHealth","Risk"]] as const;

export function EditProjectForm({projectId,initialValues}:{projectId:string;initialValues:Values}) {
  const [state,action] = useActionState(updateProjectAction,{status:"idle",values:initialValues} as ProjectActionState);
  const values={...initialValues,...state.values};
  return <form action={action} noValidate className="space-y-7"><input type="hidden" name="projectId" value={projectId}/>
    {state.message?<p role="alert" className="rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-900">{state.message}</p>:null}
    <fieldset className="space-y-5"><legend className="text-lg font-semibold">Project details</legend>{textFields.map(([name,label,max,multiline])=><div className="space-y-2" key={name}><label htmlFor={name} className="block text-sm font-medium">{label}{name!=="description"?<span aria-hidden="true" className="text-rose-700"> *</span>:<span className="text-slate-500"> (optional)</span>}</label>{multiline?<textarea id={name} name={name} rows={name==="businessObjective"?4:3} maxLength={max} required={name!=="description"} defaultValue={values[name]} className={input} aria-describedby={state.fieldErrors?.[name]?`${name}-error`:undefined}/>:<input id={name} name={name} maxLength={max} required defaultValue={values[name]} className={input} aria-describedby={state.fieldErrors?.[name]?`${name}-error`:undefined}/>}<FieldError id={`${name}-error`} errors={state.fieldErrors?.[name]}/></div>)}<div className="space-y-2"><label htmlFor="sponsorEmail" className="block text-sm font-medium">Sponsor email <span className="text-slate-500">(optional)</span></label><input id="sponsorEmail" name="sponsorEmail" type="email" defaultValue={values.sponsorEmail} className={input}/><FieldError id="sponsorEmail-error" errors={state.fieldErrors?.sponsorEmail}/></div></fieldset>
    <fieldset><legend className="text-lg font-semibold">Lifecycle and status</legend><p className="mb-4 mt-1 text-sm text-slate-600">Lifecycle phase describes where the project is; status describes its delivery condition.</p><div className="grid gap-5 sm:grid-cols-2"><Select name="lifecyclePhase" label="Lifecycle phase" options={lifecyclePhases} value={values.lifecyclePhase} errors={state.fieldErrors?.lifecyclePhase}/><Select name="status" label="Project status" options={projectStatuses} value={values.status} errors={state.fieldErrors?.status}/><DateField name="startDate" label="Start date" value={values.startDate} errors={state.fieldErrors?.startDate}/><DateField name="targetCompletionDate" label="Target completion date" value={values.targetCompletionDate} errors={state.fieldErrors?.targetCompletionDate}/></div><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><label className="flex gap-3 text-sm text-amber-950"><input type="checkbox" name="confirmTerminal" value="confirmed" className="mt-1 size-4"/><span>I confirm that selecting Completed or Cancelled will close this project.</span></label><FieldError id="terminal-error" errors={state.fieldErrors?.confirmTerminal}/></div></fieldset>
    <fieldset><legend className="mb-1 text-lg font-semibold">Health assessment</legend><p className="mb-4 text-sm text-slate-600">Every value is shown as text; color is supplementary.</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{healthFields.map(([name,label])=><Select key={name} name={name} label={`${label} health`} options={healthValues} value={values[name]} errors={state.fieldErrors?.[name]}/>)}</div></fieldset><SubmitButton idleLabel="Save changes" pendingLabel="Saving changes…"/></form>;
}
function Select({name,label,options,value,errors}:{name:string;label:string;options:readonly string[];value:string;errors?:string[]}){return <div className="space-y-2"><label htmlFor={name} className="block text-sm font-medium">{label}</label><select id={name} name={name} defaultValue={value} className={input} aria-invalid={!!errors} aria-describedby={errors?`${name}-error`:undefined}>{options.map(option=><option key={option}>{option}</option>)}</select><FieldError id={`${name}-error`} errors={errors}/></div>}
function DateField({name,label,value,errors}:{name:string;label:string;value:string;errors?:string[]}){return <div className="space-y-2"><label htmlFor={name} className="block text-sm font-medium">{label}</label><input id={name} name={name} type="date" required defaultValue={value} className={input} aria-invalid={!!errors} aria-describedby={errors?`${name}-error`:undefined}/><FieldError id={`${name}-error`} errors={errors}/></div>}
