import { expect,test,type Page } from "@playwright/test";import{randomUUID}from"node:crypto";import{createLocalUserClient,deleteLocalTestUsers,provisionLocalProjectMember}from"./local-supabase";
const suffix=randomUUID(),password=`Helm-${randomUUID()}-9a!`,projectName=`Atlas ${suffix.slice(0,8)}`;const users={admin:`helm-project-admin-${suffix}@example.test`,outsider:`helm-project-outsider-${suffix}@example.test`,member:`helm-project-member-${suffix}@example.test`,nomember:`helm-project-none-${suffix}@example.test`};const ids:string[]=[];let organizationId="",projectId="";
async function user(email:string,name:string){const c=createLocalUserClient();const{data,error}=await c.auth.signUp({email,password,options:{data:{full_name:name}}});if(error||!data.user)throw error;ids.push(data.user.id);return data.user.id}
async function login(page:Page,email:string){await page.goto("/sign-in");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await page.waitForURL(/\/(projects|onboarding)(?:\/|$)/)}
async function onboard(email:string,name:string,org:string){const c=createLocalUserClient();await c.auth.signInWithPassword({email,password});const{data,error}=await c.rpc("complete_onboarding",{p_full_name:name,p_organization_name:org});if(error)throw error;await c.auth.signOut();return data}
async function fill(page:Page){await page.getByLabel("Project name").fill(projectName);await page.getByLabel("Business objective").fill("Deliver a secure project foundation.");await page.getByLabel("Sponsor name").fill("Morgan Sponsor");await page.getByLabel("Start date").fill("2026-08-01");await page.getByLabel("Target completion date").fill("2026-12-01")}
test.describe.serial("project creation and overview",()=>{test.beforeAll(async()=>{const admin=await user(users.admin,"Admin User");await user(users.outsider,"Outside User");await user(users.member,"Member User");await user(users.nomember,"No Membership");organizationId=(await onboard(users.admin,"Admin User",`Admin Org ${suffix}`))!;await onboard(users.outsider,"Outside User",`Outside Org ${suffix}`);expect(admin).toBeTruthy()});test.afterAll(async()=>deleteLocalTestUsers(ids));
test("anonymous project creation and editing redirect to sign-in",async({page})=>{await page.goto("/projects/new");await expect(page).toHaveURL(/sign-in/);await page.goto(`/projects/${randomUUID()}/edit`);await expect(page).toHaveURL(/sign-in/)});
test("user without membership redirects to onboarding",async({page})=>{await login(page,users.nomember);await page.goto(`/projects/${randomUUID()}/edit`);await expect(page).toHaveURL(/onboarding/)});
test("administrator sees empty state and can access creation",async({page})=>{await login(page,users.admin);await expect(page.getByText("No projects yet")).toBeVisible();await page.getByRole("link",{name:"Create your first project"}).click();await expect(page.getByRole("heading",{name:"Create a project"})).toBeVisible()});
test("validates required fields, email, dates, and lifecycle",async({page})=>{await login(page,users.admin);await page.goto("/projects/new");await page.getByRole("button",{name:"Create project"}).click();await expect(page.getByText("Enter project name.")).toBeVisible();await fill(page);await page.getByLabel("Sponsor email").fill("invalid");await page.getByLabel("Target completion date").fill("2026-07-01");await page.getByLabel("Lifecycle phase").selectOption("Planning");await page.getByRole("button",{name:"Create project"}).click();await expect(page.getByText("Enter a valid sponsor email.")).toBeVisible();await expect(page.getByText("Target completion date cannot be before the start date.")).toBeVisible();await expect(page.getByText("Draft projects must be in Initiation.")).toBeVisible()});
test("mobile form and keyboard submission create the project",async({page})=>{await page.setViewportSize({width:390,height:844});await login(page,users.admin);await page.goto("/projects/new");await fill(page);expect(await page.locator("body").evaluate(b=>b.scrollWidth)).toBeLessThanOrEqual(390);await page.getByRole("button",{name:"Create project"}).focus();await page.keyboard.press("Enter");await expect(page).toHaveURL(/\/projects\/[0-9a-f-]+\?created=true/);await expect(page.getByText("Project created successfully.")).toBeVisible();projectId=new URL(page.url()).pathname.split("/").pop()!;await expect(page.getByText(projectName)).toBeVisible();await expect(page.getByText("Overall health")).toBeVisible();await expect(page.getByText("Not Assessed").first()).toBeVisible()});
test("automatic Project Manager membership exists and no duplicate project was created",async()=>{const c=createLocalUserClient();await c.auth.signInWithPassword({email:users.admin,password});const{data}=await c.from("project_members").select("access_level,project_role").eq("project_id",projectId).single();expect(data).toEqual({access_level:"Project Manager",project_role:"Project Manager"});const{data:projects}=await c.from("projects").select("id").eq("name",projectName);expect(projects).toHaveLength(1);await c.auth.signOut()});
test("project persists, appears in list, and exposes editing to its Administrator and Project Manager",async({page})=>{await login(page,users.admin);await page.goto(`/projects/${projectId}`);await page.reload();await expect(page.getByText(projectName)).toBeVisible();await expect(page.getByRole("link",{name:"Edit project"})).toBeVisible();await page.goto("/projects");await expect(page.getByText(projectName)).toBeVisible()});
test("administrator loads existing values and updates fields and health",async({page})=>{await login(page,users.admin);await page.goto(`/projects/${projectId}`);await page.getByRole("link",{name:"Edit project"}).click();await expect(page.getByLabel("Project name")).toHaveValue(projectName);await expect(page.getByLabel("Business objective")).toHaveValue("Deliver a secure project foundation.");await page.getByLabel("Project name").fill(`${projectName} Updated`);await page.getByLabel("Project description").fill("Updated through authorized editing.");await page.getByLabel("Overall health").selectOption("Green");await page.getByLabel("Risk health").selectOption("Amber");await page.getByRole("button",{name:"Save changes"}).focus();await page.keyboard.press("Enter");await expect(page).toHaveURL(/updated=true/);await expect(page.getByText("Project updated successfully.")).toBeVisible();await expect(page.getByText(`${projectName} Updated`)).toBeVisible();await expect(page.getByText("Green",{exact:true}).first()).toBeVisible();await page.reload();await expect(page.getByText("Updated through authorized editing.")).toBeVisible()});
test("edit validation rejects email, date order, lifecycle, and unconfirmed terminal status",async({page})=>{await login(page,users.admin);await page.goto(`/projects/${projectId}/edit`);await page.getByLabel("Sponsor email").fill("invalid");await page.getByLabel("Target completion date").fill("2026-01-01");await page.getByLabel("Lifecycle phase").selectOption("Closed");await page.getByLabel("Project status").selectOption("Completed");await page.getByRole("button",{name:"Save changes"}).click();await expect(page.getByText("Enter a valid sponsor email.")).toBeVisible();await expect(page.getByText("Target completion date cannot be before the start date.")).toBeVisible();await expect(page.getByText("Confirm that you intend to mark this project Completed.")).toBeVisible()});
test("mobile edit form works and ignores immutable injected fields",async({page})=>{await page.setViewportSize({width:390,height:844});await login(page,users.admin);await page.goto(`/projects/${projectId}/edit`);expect(await page.locator("body").evaluate(b=>b.scrollWidth)).toBeLessThanOrEqual(390);const editForm=page.locator("form").filter({has:page.getByRole("button",{name:"Save changes"})});await editForm.evaluate((form)=>{for(const name of ["organizationId","projectManagerId","createdBy"]){const input=document.createElement("input");input.name=name;input.value="00000000-0000-4000-8000-000000000000";form.appendChild(input)}});await page.getByLabel("Sponsor name").fill("Updated Sponsor");await page.getByRole("button",{name:"Save changes"}).click();await expect(page).toHaveURL(/updated=true/);await expect(page.getByText("Updated Sponsor")).toBeVisible()});
test("other organization cannot view or edit project",async({page})=>{await login(page,users.outsider);await page.goto(`/projects/${projectId}/edit`);await expect(page.getByRole("heading",{name:"Project not available"})).toBeVisible();await expect(page.getByText(projectName)).toHaveCount(0)});
test("ordinary member cannot create but assigned member can view",async({page})=>{provisionLocalProjectMember({userId:ids[2],email:users.member,fullName:"Member User",organizationId,projectId});await login(page,users.member);await page.goto("/projects/new");await expect(page).toHaveURL(/\/projects$/);await expect(page.getByRole("link",{name:/create project/i})).toHaveCount(0);await page.goto(`/projects/${projectId}`);await expect(page.getByText(projectName)).toBeVisible();await expect(page.getByRole("link",{name:/edit/i})).toHaveCount(0)});
test("invalid project ID reveals no details and sign-out works",async({page})=>{await login(page,users.admin);await page.goto("/projects/not-a-project");await expect(page.getByRole("heading",{name:"Project not available"})).toBeVisible();await page.goto(`/projects/${projectId}`);await page.getByRole("button",{name:"Sign out"}).click();await expect(page).toHaveURL(/signedOut=true/)});
});
