





import { expect, test, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { assignLocalProjectManager, createLocalUserClient, deleteLocalTestUsers, provisionLocalProjectMember } from "./local-supabase";

const suffix=randomUUID(),password=`Helm-${randomUUID()}-9a!`,users={admin:`decision-admin-${suffix}@example.test`,manager:`decision-manager-${suffix}@example.test`,member:`decision-member-${suffix}@example.test`,stakeholder:`decision-stake-${suffix}@example.test`,reader:`decision-read-${suffix}@example.test`,outsider:`decision-out-${suffix}@example.test`};const ids:string[]=[];let organizationId="",projectId="",managerProjectId="";
async function signup(email:string,name:string){const c=createLocalUserClient(),{data,error}=await c.auth.signUp({email,password,options:{data:{full_name:name}}});if(error||!data.user)throw error;ids.push(data.user.id);return data.user.id}
async function login(page:Page,email:string){await page.goto("/sign-in");await page.getByLabel("Email").fill(email);await page.getByLabel("Password").fill(password);await page.getByRole("button",{name:"Sign in"}).click();await page.waitForURL(/\/(projects|onboarding)(?:\/|$)/)}
const projectArgs=(name:string,organization:string)=>({p_actual_completion_date:null as unknown as string,p_budget_health:"Not Assessed",p_business_objective:"Record authoritative decisions.",p_description:"Decision fixture",p_lifecycle_phase:"Initiation",p_name:name,p_organization_id:organization,p_overall_health:"Not Assessed",p_resource_health:"Not Assessed",p_risk_health:"Not Assessed",p_schedule_health:"Not Assessed",p_scope_health:"Not Assessed",p_sponsor_email:"",p_sponsor_name:"Sponsor",p_start_date:"2026-08-01",p_status:"Draft",p_target_completion_date:"2026-12-31"});
async function fillDecision(page:Page,title:string){const form=page.getByRole("heading",{name:"Record a decision"}).locator(".." );await form.getByLabel("Title *").fill(title);await form.getByLabel("Context *").fill("The project requires a stable hosting platform.");await form.getByLabel("Decision *").fill("Use the managed enterprise platform.");await form.getByLabel("Rationale *").fill("It provides the required reliability and support.");await form.getByLabel("Alternatives considered *").fill("Self-hosting and two public-cloud vendors.");await form.getByLabel("Consequences *").fill("The team adopts the provider operating model.");await form.getByLabel("Decision-maker *").fill("Customer architecture council");await form.getByLabel("Decision date *").fill("2026-08-01");await form.getByLabel("Effective date (optional)").fill("2026-08-15");await form.getByLabel("Follow-up notes (optional)").fill("Create the rollout work manually as an Action.");return form}

test.describe.serial("project Decision Log",()=>{test.beforeAll(async()=>{const adminId=await signup(users.admin,"Decision Admin"),managerId=await signup(users.manager,"Decision Manager"),memberId=await signup(users.member,"Decision Member"),stakeId=await signup(users.stakeholder,"Decision Stakeholder"),readerId=await signup(users.reader,"Decision Reader");await signup(users.outsider,"Decision Outsider");const c=createLocalUserClient();await c.auth.signInWithPassword({email:users.admin,password});const onboard=await c.rpc("complete_onboarding",{p_full_name:"Decision Admin",p_organization_name:`Decision Org ${suffix}`});if(onboard.error)throw onboard.error;organizationId=onboard.data;const project=await c.rpc("create_project",projectArgs(`Decision Project ${suffix.slice(0,8)}`,organizationId));if(project.error)throw project.error;projectId=project.data;const managerProject=await c.rpc("create_project",projectArgs(`Manager Decision Project ${suffix.slice(0,8)}`,organizationId));if(managerProject.error)throw managerProject.error;managerProjectId=managerProject.data;await c.auth.signOut();provisionLocalProjectMember({userId:managerId,email:users.manager,fullName:"Decision Manager",organizationId,projectId:managerProjectId,accessLevel:"Project Manager"});assignLocalProjectManager(managerId,managerProjectId);provisionLocalProjectMember({userId:memberId,email:users.member,fullName:"Decision Member",organizationId,projectId});provisionLocalProjectMember({userId:stakeId,email:users.stakeholder,fullName:"Decision Stakeholder",organizationId,projectId,accessLevel:"Stakeholder"});provisionLocalProjectMember({userId:readerId,email:users.reader,fullName:"Decision Reader",organizationId,projectId,accessLevel:"Read Only"});const o=createLocalUserClient();await o.auth.signInWithPassword({email:users.outsider,password});const other=await o.rpc("complete_onboarding",{p_full_name:"Decision Outsider",p_organization_name:`Other Decision Org ${suffix}`});if(other.error)throw other.error;await o.auth.signOut();expect(adminId).toBeTruthy()});test.afterAll(async()=>deleteLocalTestUsers(ids));
test("anonymous redirect and cross-organization access are non-revealing",async({page})=>{await page.goto(`/projects/${projectId}/decisions`);await expect(page).toHaveURL(/sign-in/);await login(page,users.outsider);await page.goto(`/projects/${projectId}/decisions`);await expect(page.getByRole("heading",{name:"Project not available"})).toBeVisible()});
test("Administrator records and corrects a complete decision on mobile",async({page})=>{await page.setViewportSize({width:390,height:844});await login(page,users.admin);await page.goto(`/projects/${projectId}`);await page.getByRole("link",{name:"Decision Log"}).click();const form=await fillDecision(page,"Hosting platform selected");await form.getByRole("button",{name:"Record decision"}).focus();await page.keyboard.press("Enter");await expect(page.getByRole("status")).toContainText("Decision recorded");let card=page.locator("article").filter({hasText:"Hosting platform selected"});for(const text of["Customer architecture council","The project requires a stable hosting platform.","Use the managed enterprise platform.","It provides the required reliability and support.","Self-hosting and two public-cloud vendors.","The team adopts the provider operating model.","Create the rollout work manually as an Action."])await expect(card.getByText(text)).toBeVisible();await page.reload();card=page.locator("article").filter({hasText:"Hosting platform selected"});await expect(card.getByText("Aug 15, 2026")).toBeVisible();const c=createLocalUserClient();await c.auth.signInWithPassword({email:users.admin,password});const actions=await c.from("project_actions").select("id",{count:"exact",head:true}).eq("project_id",projectId);expect(actions.count).toBe(0);await card.getByRole("link",{name:"Correct decision record Hosting platform selected"}).click();await expect(page.getByText(/Use a correction only to fix an inaccurate record/)).toBeVisible();const correction=page.getByRole("heading",{name:/Correct decision record:/}).locator("..");await correction.getByLabel("Decision *").fill("Use the managed enterprise hosting platform.");await correction.getByLabel("Correction reason *").fill("The original platform name was incomplete.");await correction.getByRole("button",{name:"Submit correction"}).click();await expect(correction.getByText(/Confirm that this is a correction/)).toBeVisible();await correction.getByLabel(/I confirm this corrects/).check();await correction.getByRole("button",{name:"Submit correction"}).click();await expect(page.getByRole("status")).toContainText("corrected");await page.reload();card=page.locator("article").filter({hasText:"Hosting platform selected"});await expect(card.getByText("Corrected",{exact:true})).toBeVisible();await expect(card.getByText("The original platform name was incomplete.")).toBeVisible();await expect(card.getByText("Latest correction").locator("..").getByText(/by Decision Admin/)).toBeVisible();expect(await page.locator("body").evaluate(body=>body.scrollWidth)).toBeLessThanOrEqual(390)});
test("required validation preserves safe values",async({page})=>{await login(page,users.admin);await page.goto(`/projects/${projectId}/decisions`);await page.getByLabel("Title *").fill("Preserved title");await page.getByRole("button",{name:"Record decision"}).click();await expect(page.getByText("Review the highlighted fields and try again.")).toBeVisible();await expect(page.getByLabel("Title *")).toHaveValue("Preserved title")});
test("actual assigned Project Manager records independently",async({page})=>{await login(page,users.manager);await page.goto(`/projects/${managerProjectId}/decisions`);const form=await fillDecision(page,"Manager-owned choice");await form.getByRole("button",{name:"Record decision"}).click();await expect(page.getByText("Decision recorded.")).toBeVisible();await page.reload();await expect(page.locator("article").filter({hasText:"Manager-owned choice"})).toBeVisible()});
for(const [role,email]of [["Project Member",users.member],["Stakeholder",users.stakeholder],["Read Only",users.reader]]as const)test(`${role} has read-only access and decision-maker naming grants no mutation`,async({page})=>{await login(page,email);await page.goto(`/projects/${projectId}/decisions`);await expect(page.locator("article").filter({hasText:"Hosting platform selected"})).toBeVisible();await expect(page.getByRole("heading",{name:"Record a decision"})).toHaveCount(0);await expect(page.getByRole("link",{name:/Correct decision record/})).toHaveCount(0);await expect(page.getByRole("button",{name:/delete/i})).toHaveCount(0)});
});
