import{z}from"zod";
export const changeCategories=["Scope","Schedule","Budget","Resources","Quality","Technical","Risk","Other"]as const;
export const changeStatuses=["Draft","Submitted","Approved","Rejected","Withdrawn","In Implementation","Implemented","Not Implemented"]as const;
const text=(label:string,max=4000)=>z.string().trim().min(1,`${label} is required.`).max(max,`${label} must be ${max} characters or fewer.`);const optional=z.string().trim().max(4000).transform(v=>v||null);const date=z.iso.date();
const base={projectId:z.uuid(),title:text("Title",200),description:text("Description"),reason:text("Reason"),category:z.enum(changeCategories),requesterName:text("Requester",200),requestedDate:date,scopeImpact:optional,scheduleImpact:optional,budgetImpact:optional,resourceImpact:optional,qualityImpact:optional,riskImpact:optional,recommendation:optional};
function future(v:{requestedDate:string},c:z.RefinementCtx){if(v.requestedDate>new Date().toISOString().slice(0,10))c.addIssue({code:"custom",path:["requestedDate"],message:"Requested date cannot be in the future."})}
export const createChangeSchema=z.object({...base,operation:z.literal("create")}).strict().superRefine(future);export const updateChangeSchema=z.object({...base,operation:z.literal("update"),changeRequestId:z.uuid()}).strict().superRefine(future);export const changeDraftSchema=z.discriminatedUnion("operation",[createChangeSchema,updateChangeSchema]);
const confirmed=z.literal("confirmed",{error:"Confirm this action."});const id=z.object({projectId:z.uuid(),changeRequestId:z.uuid()});
export const submitChangeSchema=id.extend({confirm:confirmed});export const withdrawChangeSchema=id.extend({notes:text("Withdrawal notes"),confirm:confirmed});export const rejectChangeSchema=id.extend({notes:text("Decision notes"),confirm:confirmed});
export const approveChangeSchema=id.extend({notes:text("Decision notes"),ownerMembershipId:z.uuid("Select an eligible implementation owner."),targetDate:date,confirm:confirmed});export const implementationPlanSchema=id.extend({ownerMembershipId:z.uuid("Select an eligible implementation owner."),targetDate:date});export const startImplementationSchema=id.extend({confirm:confirmed});export const implementedSchema=id.extend({notes:text("Implementation outcome notes"),confirm:confirmed});export const notImplementedSchema=implementedSchema;
export const submissionAssessmentSchema=z.object({scopeImpact:text("Scope impact"),scheduleImpact:text("Schedule impact"),budgetImpact:text("Budget impact"),resourceImpact:text("Resource impact"),qualityImpact:text("Quality impact"),riskImpact:text("Risk impact"),recommendation:text("Recommendation")});
