import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { z } from "zod";
import { ApplicationShell } from "@/features/organizations/components/application-shell";
import { getActiveOrganizationMembership } from "@/features/organizations/queries";
import { AddTeamMemberForm, MembershipActionForm } from "@/features/project-team/components/team-action-form";
import { getEligibleProjectMembers, getProjectTeam } from "@/features/project-team/queries";
import { canEditProject, getAuthorizedProject } from "@/features/projects/queries";
import { createClient } from "@/lib/supabase/server";

export default async function ProjectTeamPage({params,searchParams}:{params:Promise<{projectId:string}>;searchParams:Promise<{updated?:string}>}) {
 const supabase=await createClient();const{data,error}=await supabase.auth.getUser();if(error||!data.user)redirect("/sign-in");const membership=await getActiveOrganizationMembership(supabase,data.user.id);if(membership.status==="none")redirect("/onboarding");if(membership.status==="error")throw new Error("Unable to verify organization access.");const{projectId}=await params;if(!z.uuid().safeParse(projectId).success)notFound();const{data:project,error:projectError}=await getAuthorizedProject(supabase,projectId);if(projectError||!project)notFound();const canManage=await canEditProject(supabase,data.user.id,project,membership.membership);const{data:roster,error:rosterError}=await getProjectTeam(supabase,project.id);if(rosterError)throw new Error("Unable to load project team.");const eligibleResult=canManage?await getEligibleProjectMembers(supabase,project.id):{data:[],error:null};if(eligibleResult.error)throw new Error("Unable to load eligible organization members.");const{data:profile}=await supabase.from("profiles").select("full_name").eq("id",data.user.id).maybeSingle();const query=await searchParams;
 return <ApplicationShell organizationName={membership.membership.organizationName} userLabel={profile?.full_name||data.user.email||"Signed-in user"}><section className="mx-auto max-w-6xl px-5 py-10 sm:px-8">{query.updated==="true"?<p role="status" className="mb-6 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-900">Project team access updated successfully.</p>:null}<Link href={`/projects/${project.id}`} className="text-sm font-semibold underline underline-offset-4">Back to project overview</Link><header className="mt-5"><p className="text-sm font-semibold text-sky-700">{project.name}</p><h1 className="mt-1 text-3xl font-semibold">Project team</h1><p className="mt-2 text-slate-600">Review active and inactive project access. The assigned Project Manager membership is protected.</p></header>{canManage?<section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-semibold">Add team access</h2><div className="mt-5"><AddTeamMemberForm projectId={project.id} eligible={eligibleResult.data??[]}/></div></section>:null}<section className="mt-8"><h2 className="text-xl font-semibold">Current roster</h2>{!roster?.length?<p className="mt-4 rounded-xl border border-dashed border-slate-300 p-5 text-slate-600">No project memberships are available.</p>:<div className="mt-4 grid gap-4 sm:grid-cols-2">{roster.map(member=><article key={member.membership_id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-950">{member.full_name||member.email}</h3><p className="mt-1 text-sm text-slate-600">{member.email}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${member.active?"bg-emerald-50 text-emerald-900":"bg-slate-100 text-slate-700"}`}>{member.active?"Active":"Inactive"}</span></div><p className="mt-3 text-sm font-medium">Access level: {member.access_level}</p>{member.is_assigned_manager?<p className="mt-3 text-sm text-slate-600">Assigned Project Manager — protected membership</p>:canManage?<MembershipActionForm projectId={project.id} userId={member.user_id} accessLevel={member.access_level} active={member.active}/>:null}</article>)}</div>}</section></section></ApplicationShell>;
}
