import Link from"next/link";import{PublishForm}from"./publish-form";
export type ReportRow=Record<string,unknown>&{id:string;project_id:string;reporting_period_start:string;reporting_period_end:string;status:string;executive_summary:string;accomplishments:string;planned_work:string;concerns:string|null;decisions_required:string|null;support_required:string|null;published_at:string|null;created_at:string;last_edited_at:string;project_name_snapshot:string|null;project_status_snapshot:string|null;project_lifecycle_phase_snapshot:string|null};
const day=(x:string)=>new Intl.DateTimeFormat("en",{dateStyle:"medium",timeZone:"UTC"}).format(new Date(`${x}T00:00:00Z`));const time=(x:string)=>new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(x));
const health=["overall","scope","schedule","budget","resource","risk"];
export function ReportCard({r,projectId}:{r:ReportRow;projectId:string}){return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><h3 className="font-semibold">{day(r.reporting_period_start)} – {day(r.reporting_period_end)}</h3><span className="rounded-full border px-3 py-1 text-xs font-semibold">{r.status}</span></div><p className="mt-3 line-clamp-3 text-sm text-slate-700">{r.executive_summary}</p><dl className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-3">{health.map(h=><div key={h}><dt className="capitalize text-xs text-slate-500">{h}</dt><dd className="text-sm font-semibold">{String(r[`${h}_health`])}</dd></div>)}</dl><Link href={`/projects/${projectId}/status-reports/${r.id}`} aria-label={`Open ${r.status} status report for ${r.reporting_period_start} to ${r.reporting_period_end}`} className="mt-5 inline-block font-semibold underline">Open report</Link></article>}
export function PublishedReport({r}:{r:ReportRow}){return <div className="space-y-7"><section className="rounded-2xl border border-sky-200 bg-sky-50 p-5"><p className="font-semibold">Published historical snapshot</p><p className="mt-1 text-sm">Captured at publication on {time(r.published_at!)}. Source data was copied at publication and was not reconstructed as of the reporting-period end.</p></section><section><h2 className="text-xl font-semibold">{r.project_name_snapshot}</h2><dl className="mt-3 grid gap-3 sm:grid-cols-2"><Pair l="Project status" v={r.project_status_snapshot}/><Pair l="Lifecycle phase" v={r.project_lifecycle_phase_snapshot}/>{health.map(h=><Pair key={h} l={`${h[0].toUpperCase()+h.slice(1)} health`} v={r[`${h}_health`]}/>)}</dl></section><section><h2 className="text-xl font-semibold">Narrative</h2><dl className="mt-3 grid gap-5"><Pair l="Executive summary" v={r.executive_summary}/><Pair l="Accomplishments" v={r.accomplishments}/><Pair l="Planned work" v={r.planned_work}/>{[["Concerns",r.concerns],["Decisions required",r.decisions_required],["Support required",r.support_required]].filter(x=>x[1]).map(x=><Pair key={String(x[0])} l={String(x[0])} v={x[1]}/>)}</dl></section><section><h2 className="text-xl font-semibold">Publication-time source snapshots</h2><div className="mt-3 grid gap-4">{[["Upcoming Milestones",r.upcoming_milestones_snapshot],["Top Risks",r.top_risks_snapshot],["Top Issues",r.top_issues_snapshot],["Overdue Actions",r.overdue_actions_snapshot],["Recent Decisions",r.recent_decisions_snapshot]].map(([label,value])=><Snapshot key={String(label)} label={String(label)} value={value}/>)}</div></section></div>}
function Pair({l,v}:{l:string;v:unknown}){return <div className="min-w-0"><dt className="text-sm font-semibold">{l}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm text-slate-700">{String(v??"")}</dd></div>}
function Snapshot({label,value}:{label:string;value:unknown}){const s=(value??{total:0,items:[]})as{total:number;items:Record<string,unknown>[]};return <article className="rounded-xl border p-4"><h3 className="font-semibold">{label} ({s.total})</h3>{s.items.length?<div className="mt-3 grid gap-3">{s.items.map((item,i)=><dl key={i} className="min-w-0 rounded-lg bg-slate-50 p-3">{Object.entries(item).filter(([,v])=>v!==null).map(([k,v])=><Pair key={k} l={k.replaceAll("_"," ")} v={v}/>)}</dl>)}</div>:<p className="mt-2 text-sm text-slate-600">No matching records at publication.</p>}</article>}
export function PublishPanel({projectId,reportId}:{projectId:string;reportId:string}){return <section className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold">Publish historical snapshot</h2><p className="mt-1 text-sm">Publication copies the current source context and permanently locks this report. It cannot be edited, deleted, reopened, or unpublished.</p><PublishForm projectId={projectId} reportId={reportId}/></section>}
