alter table public.project_risks add constraint project_risks_id_project_unique unique(id,project_id);

create table public.project_issues (
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete restrict,
 originating_risk_id uuid, title text not null, description text not null, category text not null, severity text not null,
 current_impact text not null, owner_membership_id uuid not null references public.project_members(id) on delete restrict,
 identified_date date not null default current_date, target_resolution_date date not null, resolution_plan text not null,
 status text not null default 'Open', blocked_reason text,
 resolution_notes text, resolved_by uuid references public.profiles(id) on delete restrict, resolved_at timestamptz,
 cancellation_notes text, cancelled_by uuid references public.profiles(id) on delete restrict, cancelled_at timestamptz,
 created_by uuid not null references public.profiles(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint project_issues_origin_project_fkey foreign key(originating_risk_id,project_id) references public.project_risks(id,project_id) on delete restrict,
 constraint project_issues_title_check check(char_length(btrim(title)) between 1 and 200),
 constraint project_issues_description_check check(char_length(btrim(description)) between 1 and 4000),
 constraint project_issues_category_check check(category in('Scope','Schedule','Cost','Resources','Technical','Quality','Supplier','Compliance','Operational','Other')),
 constraint project_issues_severity_check check(severity in('Low','Medium','High','Critical')),
 constraint project_issues_impact_check check(char_length(btrim(current_impact)) between 1 and 4000),
 constraint project_issues_plan_check check(char_length(btrim(resolution_plan)) between 1 and 4000),
 constraint project_issues_dates_check check(target_resolution_date>=identified_date),
 constraint project_issues_status_check check(status in('Open','In Progress','Blocked','Resolved','Cancelled')),
 constraint project_issues_blocked_check check(blocked_reason is null or char_length(btrim(blocked_reason)) between 1 and 4000),
 constraint project_issues_resolution_check check(resolution_notes is null or char_length(btrim(resolution_notes)) between 1 and 4000),
 constraint project_issues_cancellation_check check(cancellation_notes is null or char_length(btrim(cancellation_notes)) between 1 and 4000),
 constraint project_issues_state_check check(
  (status in('Open','In Progress') and blocked_reason is null and resolution_notes is null and resolved_by is null and resolved_at is null and cancellation_notes is null and cancelled_by is null and cancelled_at is null) or
  (status='Blocked' and blocked_reason is not null and resolution_notes is null and resolved_by is null and resolved_at is null and cancellation_notes is null and cancelled_by is null and cancelled_at is null) or
  (status='Resolved' and blocked_reason is null and resolution_notes is not null and resolved_by is not null and resolved_at is not null and cancellation_notes is null and cancelled_by is null and cancelled_at is null) or
  (status='Cancelled' and blocked_reason is null and cancellation_notes is not null and cancelled_by is not null and cancelled_at is not null and resolution_notes is null and resolved_by is null and resolved_at is null)
 )
);
create index project_issues_project_status_target_idx on public.project_issues(project_id,status,target_resolution_date,id);
create index project_issues_project_owner_status_idx on public.project_issues(project_id,owner_membership_id,status);
create index project_issues_project_severity_target_idx on public.project_issues(project_id,severity,target_resolution_date,id);
create index project_issues_origin_idx on public.project_issues(project_id,originating_risk_id) where originating_risk_id is not null;

create function private.issue_owner_is_eligible(p_project_id uuid,p_membership_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.project_members pm join public.projects p on p.id=pm.project_id join public.organization_members om on om.organization_id=p.organization_id and om.user_id=pm.user_id and om.status='Active' where pm.id=p_membership_id and pm.project_id=p_project_id and pm.left_at is null and(pm.access_level='Project Member' or(pm.access_level='Project Manager' and pm.user_id=p.project_manager_id))) $$;
create function private.issue_origin_is_eligible(p_project_id uuid,p_risk_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select p_risk_id is null or exists(select 1 from public.project_risks r where r.id=p_risk_id and r.project_id=p_project_id and r.status='Realized') $$;
create function private.protect_project_issue() returns trigger language plpgsql security definer set search_path='' as $$ begin
 if tg_op='INSERT' then if new.status<>'Open' or new.created_by<>auth.uid() or new.identified_date>current_date or not private.issue_origin_is_eligible(new.project_id,new.originating_risk_id) or new.blocked_reason is not null or new.resolution_notes is not null or new.resolved_by is not null or new.resolved_at is not null or new.cancellation_notes is not null or new.cancelled_by is not null or new.cancelled_at is not null then raise exception 'New issues must use trusted valid initial values.' using errcode='23514';end if;
 else if new.id is distinct from old.id or new.project_id is distinct from old.project_id or new.originating_risk_id is distinct from old.originating_risk_id or new.identified_date is distinct from old.identified_date or new.created_by is distinct from old.created_by or new.created_at is distinct from old.created_at then raise exception 'Issue identity fields cannot be changed.' using errcode='42501';end if;if old.status in('Resolved','Cancelled') then raise exception 'Terminal issues cannot be changed.' using errcode='42501';end if;end if;
 new.title:=btrim(new.title);new.description:=btrim(new.description);new.current_impact:=btrim(new.current_impact);new.resolution_plan:=btrim(new.resolution_plan);new.blocked_reason:=nullif(btrim(new.blocked_reason),'');new.resolution_notes:=nullif(btrim(new.resolution_notes),'');new.cancellation_notes:=nullif(btrim(new.cancellation_notes),'');new.updated_at:=now();return new;end;$$;
create trigger project_issues_protect before insert or update on public.project_issues for each row execute function private.protect_project_issue();
alter table public.project_issues enable row level security;
create policy project_issues_select_project_access on public.project_issues for select to authenticated using(private.has_project_access(project_id));
revoke all on public.project_issues from anon,authenticated;grant select on public.project_issues to authenticated;

create function public.create_project_issue(p_project_id uuid,p_title text,p_description text,p_category text,p_severity text,p_current_impact text,p_owner_membership_id uuid,p_identified_date date,p_target_resolution_date date,p_resolution_plan text,p_originating_risk_id uuid default null) returns public.project_issues language plpgsql security definer set search_path='' as $$ declare persisted public.project_issues%rowtype;begin
 if auth.uid() is null or not private.can_manage_project(p_project_id) then raise exception 'Issue creation is not permitted.' using errcode='42501';end if;
 if p_identified_date>current_date then raise exception 'Identified date cannot be in the future.' using errcode='22023';end if;
 if not private.issue_owner_is_eligible(p_project_id,p_owner_membership_id) then raise exception 'The selected issue owner is not eligible.' using errcode='23514';end if;
 if not private.issue_origin_is_eligible(p_project_id,p_originating_risk_id) then raise exception 'The selected originating risk is not eligible.' using errcode='23514';end if;
 insert into public.project_issues(project_id,originating_risk_id,title,description,category,severity,current_impact,owner_membership_id,identified_date,target_resolution_date,resolution_plan,created_by) values(p_project_id,p_originating_risk_id,p_title,p_description,p_category,p_severity,p_current_impact,p_owner_membership_id,p_identified_date,p_target_resolution_date,p_resolution_plan,auth.uid()) returning * into persisted;return persisted;end;$$;
create function public.update_project_issue(p_issue_id uuid,p_title text,p_description text,p_category text,p_severity text,p_current_impact text,p_owner_membership_id uuid,p_target_resolution_date date,p_resolution_plan text) returns public.project_issues language plpgsql security definer set search_path='' as $$ declare current_issue public.project_issues%rowtype;persisted public.project_issues%rowtype;begin
 if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into current_issue from public.project_issues where id=p_issue_id for update;
 if current_issue.id is null or not private.can_manage_project(current_issue.project_id) or current_issue.status in('Resolved','Cancelled') then raise exception 'Issue update is not permitted.' using errcode='42501';end if;
 if not private.issue_owner_is_eligible(current_issue.project_id,p_owner_membership_id) then raise exception 'The selected issue owner is not eligible.' using errcode='23514';end if;
 update public.project_issues set title=p_title,description=p_description,category=p_category,severity=p_severity,current_impact=p_current_impact,owner_membership_id=p_owner_membership_id,target_resolution_date=p_target_resolution_date,resolution_plan=p_resolution_plan where id=p_issue_id returning * into persisted;return persisted;end;$$;
create function public.transition_project_issue_active(p_issue_id uuid,p_target_status text,p_blocked_reason text default null) returns public.project_issues language plpgsql security definer set search_path='' as $$ declare current_issue public.project_issues%rowtype;persisted public.project_issues%rowtype;begin
 if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into current_issue from public.project_issues where id=p_issue_id for update;
 if current_issue.id is null or not private.can_manage_project(current_issue.project_id) or current_issue.status in('Resolved','Cancelled') then raise exception 'Issue transition is not permitted.' using errcode='42501';end if;
 if p_target_status not in('Open','In Progress','Blocked') or(current_issue.status=p_target_status and p_target_status<>'Blocked') then raise exception 'Unsupported issue transition.' using errcode='22023';end if;
 if p_target_status='Blocked' and nullif(btrim(p_blocked_reason),'') is null then raise exception 'A meaningful blocked reason is required.' using errcode='22023';end if;
 update public.project_issues set status=p_target_status,blocked_reason=case when p_target_status='Blocked' then btrim(p_blocked_reason) end where id=p_issue_id returning * into persisted;return persisted;end;$$;
create function public.resolve_project_issue(p_issue_id uuid,p_resolution_notes text) returns public.project_issues language plpgsql security definer set search_path='' as $$ declare current_issue public.project_issues%rowtype;persisted public.project_issues%rowtype;begin if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into current_issue from public.project_issues where id=p_issue_id for update;if current_issue.id is null or not private.can_manage_project(current_issue.project_id) or current_issue.status in('Resolved','Cancelled') then raise exception 'Issue resolution is not permitted.' using errcode='42501';end if;if nullif(btrim(p_resolution_notes),'') is null then raise exception 'Meaningful resolution notes are required.' using errcode='22023';end if;update public.project_issues set status='Resolved',blocked_reason=null,resolution_notes=btrim(p_resolution_notes),resolved_by=auth.uid(),resolved_at=now() where id=p_issue_id returning * into persisted;return persisted;end;$$;
create function public.cancel_project_issue(p_issue_id uuid,p_cancellation_notes text) returns public.project_issues language plpgsql security definer set search_path='' as $$ declare current_issue public.project_issues%rowtype;persisted public.project_issues%rowtype;begin if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into current_issue from public.project_issues where id=p_issue_id for update;if current_issue.id is null or not private.can_manage_project(current_issue.project_id) or current_issue.status in('Resolved','Cancelled') then raise exception 'Issue cancellation is not permitted.' using errcode='42501';end if;if nullif(btrim(p_cancellation_notes),'') is null then raise exception 'Meaningful cancellation notes are required.' using errcode='22023';end if;update public.project_issues set status='Cancelled',blocked_reason=null,cancellation_notes=btrim(p_cancellation_notes),cancelled_by=auth.uid(),cancelled_at=now() where id=p_issue_id returning * into persisted;return persisted;end;$$;

create function public.get_project_issues(p_project_id uuid) returns table(id uuid,project_id uuid,originating_risk_id uuid,title text,description text,category text,severity text,current_impact text,owner_membership_id uuid,owner_user_id uuid,owner_name text,owner_access_level text,owner_is_eligible boolean,identified_date date,target_resolution_date date,resolution_plan text,status text,blocked_reason text,resolution_notes text,resolved_by uuid,resolved_at timestamptz,resolved_by_name text,cancellation_notes text,cancelled_by uuid,cancelled_at timestamptz,cancelled_by_name text,created_by uuid,created_by_name text,created_at timestamptz,updated_at timestamptz,originating_risk_title text,originating_risk_status text,originating_risk_realized_at timestamptz) language sql stable security definer set search_path='' as $$ select i.id,i.project_id,i.originating_risk_id,i.title,i.description,i.category,i.severity,i.current_impact,i.owner_membership_id,pm.user_id,op.full_name,pm.access_level,private.issue_owner_is_eligible(i.project_id,i.owner_membership_id),i.identified_date,i.target_resolution_date,i.resolution_plan,i.status,i.blocked_reason,i.resolution_notes,i.resolved_by,i.resolved_at,rp.full_name,i.cancellation_notes,i.cancelled_by,i.cancelled_at,cp.full_name,i.created_by,creator.full_name,i.created_at,i.updated_at,r.title,r.status,r.realized_at from public.project_issues i join public.project_members pm on pm.id=i.owner_membership_id join public.profiles op on op.id=pm.user_id join public.profiles creator on creator.id=i.created_by left join public.profiles rp on rp.id=i.resolved_by left join public.profiles cp on cp.id=i.cancelled_by left join public.project_risks r on r.id=i.originating_risk_id where i.project_id=p_project_id and private.has_project_access(p_project_id) order by case when i.status in('Resolved','Cancelled') then 1 else 0 end,case when i.status not in('Resolved','Cancelled') and not private.issue_owner_is_eligible(i.project_id,i.owner_membership_id) then 0 else 1 end,case when i.status='Blocked' then 0 else 1 end,case when i.status not in('Resolved','Cancelled') and i.target_resolution_date<current_date then 0 else 1 end,case when i.status not in('Resolved','Cancelled') and i.target_resolution_date=current_date then 0 else 1 end,case i.severity when 'Critical' then 0 when 'High' then 1 when 'Medium' then 2 else 3 end,i.target_resolution_date,case when i.status in('Resolved','Cancelled') then coalesce(i.resolved_at,i.cancelled_at) end desc,i.created_at,i.id $$;
create function public.get_eligible_issue_owners(p_project_id uuid) returns table(membership_id uuid,user_id uuid,full_name text,access_level text) language plpgsql stable security definer set search_path='' as $$ begin if auth.uid() is null or not private.can_manage_project(p_project_id) then raise exception 'Issue management is not permitted.' using errcode='42501';end if;return query select pm.id,pm.user_id,pr.full_name,pm.access_level from public.project_members pm join public.profiles pr on pr.id=pm.user_id join public.projects p on p.id=pm.project_id join public.organization_members om on om.organization_id=p.organization_id and om.user_id=pm.user_id and om.status='Active' where pm.project_id=p_project_id and pm.left_at is null and(pm.access_level='Project Member' or(pm.access_level='Project Manager' and pm.user_id=p.project_manager_id)) order by pr.full_name,pm.id;end;$$;
create function public.get_eligible_issue_origins(p_project_id uuid) returns table(risk_id uuid,title text,realized_at timestamptz) language plpgsql stable security definer set search_path='' as $$ begin if auth.uid() is null or not private.can_manage_project(p_project_id) then raise exception 'Issue management is not permitted.' using errcode='42501';end if;return query select r.id,r.title,r.realized_at from public.project_risks r where r.project_id=p_project_id and r.status='Realized' order by r.realized_at desc,r.id;end;$$;

revoke all on function private.issue_owner_is_eligible(uuid,uuid),private.issue_origin_is_eligible(uuid,uuid),private.protect_project_issue() from public;
revoke all on function public.create_project_issue(uuid,text,text,text,text,text,uuid,date,date,text,uuid),public.update_project_issue(uuid,text,text,text,text,text,uuid,date,text),public.transition_project_issue_active(uuid,text,text),public.resolve_project_issue(uuid,text),public.cancel_project_issue(uuid,text),public.get_project_issues(uuid),public.get_eligible_issue_owners(uuid),public.get_eligible_issue_origins(uuid) from public;
grant execute on function public.create_project_issue(uuid,text,text,text,text,text,uuid,date,date,text,uuid),public.update_project_issue(uuid,text,text,text,text,text,uuid,date,text),public.transition_project_issue_active(uuid,text,text),public.resolve_project_issue(uuid,text),public.cancel_project_issue(uuid,text),public.get_project_issues(uuid),public.get_eligible_issue_owners(uuid),public.get_eligible_issue_origins(uuid) to authenticated;
