create table public.project_dependencies(
 id uuid primary key default gen_random_uuid(), project_id uuid not null references public.projects(id) on delete restrict,
 title text not null, description text not null, classification text not null, provider_name text not null, required_outcome text not null, required_for text not null, impact_if_missed text not null, management_plan text not null,
 owner_membership_id uuid not null references public.project_members(id) on delete restrict, identified_date date not null, needed_by_date date not null, status text not null default 'Identified', satisfaction_evidence text, outcome_notes text,
 satisfied_by uuid references public.profiles(id) on delete restrict, satisfied_at timestamptz, failed_by uuid references public.profiles(id) on delete restrict, failed_at timestamptz, no_longer_required_by uuid references public.profiles(id) on delete restrict, no_longer_required_at timestamptz,
 created_by uuid not null references public.profiles(id) on delete restrict, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint project_dependencies_title_check check(char_length(btrim(title)) between 1 and 200), constraint project_dependencies_description_check check(char_length(btrim(description)) between 1 and 4000),
 constraint project_dependencies_classification_check check(classification in('Internal','External')), constraint project_dependencies_provider_check check(char_length(btrim(provider_name)) between 1 and 200),
 constraint project_dependencies_outcome_check check(char_length(btrim(required_outcome)) between 1 and 4000), constraint project_dependencies_required_for_check check(char_length(btrim(required_for)) between 1 and 4000), constraint project_dependencies_impact_check check(char_length(btrim(impact_if_missed)) between 1 and 4000), constraint project_dependencies_plan_check check(char_length(btrim(management_plan)) between 1 and 4000),
 constraint project_dependencies_dates_check check(needed_by_date>=identified_date), constraint project_dependencies_status_check check(status in('Identified','Confirmed','In Progress','At Risk','Satisfied','Failed','No Longer Required')),
 constraint project_dependencies_evidence_check check(satisfaction_evidence is null or char_length(btrim(satisfaction_evidence)) between 1 and 4000), constraint project_dependencies_notes_check check(outcome_notes is null or char_length(btrim(outcome_notes)) between 1 and 4000),
 constraint project_dependencies_state_check check(
  (status in('Identified','Confirmed','In Progress','At Risk') and satisfaction_evidence is null and outcome_notes is null and satisfied_by is null and satisfied_at is null and failed_by is null and failed_at is null and no_longer_required_by is null and no_longer_required_at is null) or
  (status='Satisfied' and satisfaction_evidence is not null and outcome_notes is not null and satisfied_by is not null and satisfied_at is not null and failed_by is null and failed_at is null and no_longer_required_by is null and no_longer_required_at is null) or
  (status='Failed' and satisfaction_evidence is null and outcome_notes is not null and failed_by is not null and failed_at is not null and satisfied_by is null and satisfied_at is null and no_longer_required_by is null and no_longer_required_at is null) or
  (status='No Longer Required' and satisfaction_evidence is null and outcome_notes is not null and no_longer_required_by is not null and no_longer_required_at is not null and satisfied_by is null and satisfied_at is null and failed_by is null and failed_at is null)));
create index project_dependencies_project_status_due_idx on public.project_dependencies(project_id,status,needed_by_date,id); create index project_dependencies_project_owner_status_idx on public.project_dependencies(project_id,owner_membership_id,status);
create function private.dependency_owner_is_eligible(p_project_id uuid,p_membership_id uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.project_members pm join public.projects p on p.id=pm.project_id join public.organization_members om on om.organization_id=p.organization_id and om.user_id=pm.user_id and om.status='Active' where pm.id=p_membership_id and pm.project_id=p_project_id and pm.left_at is null and(pm.access_level='Project Member' or(pm.access_level='Project Manager' and pm.user_id=p.project_manager_id)))$$;
create function private.protect_project_dependency() returns trigger language plpgsql security definer set search_path='' as $$begin
 if tg_op='INSERT' then if new.status<>'Identified' or new.created_by<>auth.uid() or new.identified_date>current_date or new.satisfaction_evidence is not null or new.outcome_notes is not null or new.satisfied_by is not null or new.satisfied_at is not null or new.failed_by is not null or new.failed_at is not null or new.no_longer_required_by is not null or new.no_longer_required_at is not null then raise exception 'New dependencies must use trusted initial values.' using errcode='23514'; end if;
 else if new.id is distinct from old.id or new.project_id is distinct from old.project_id or new.identified_date is distinct from old.identified_date or new.created_by is distinct from old.created_by or new.created_at is distinct from old.created_at then raise exception 'Dependency identity fields cannot be changed.' using errcode='42501'; end if; if old.status in('Satisfied','Failed','No Longer Required') then raise exception 'Terminal dependencies cannot be changed.' using errcode='42501'; end if; end if;
 new.title:=btrim(new.title);new.description:=btrim(new.description);new.provider_name:=btrim(new.provider_name);new.required_outcome:=btrim(new.required_outcome);new.required_for:=btrim(new.required_for);new.impact_if_missed:=btrim(new.impact_if_missed);new.management_plan:=btrim(new.management_plan);new.satisfaction_evidence:=nullif(btrim(new.satisfaction_evidence),'');new.outcome_notes:=nullif(btrim(new.outcome_notes),'');new.updated_at:=now();return new;end;$$;
create trigger project_dependencies_protect before insert or update on public.project_dependencies for each row execute function private.protect_project_dependency(); alter table public.project_dependencies enable row level security; create policy project_dependencies_select_project_access on public.project_dependencies for select to authenticated using(private.has_project_access(project_id)); revoke all on public.project_dependencies from anon,authenticated; grant select on public.project_dependencies to authenticated;
create function public.create_project_dependency(p_project_id uuid,p_title text,p_description text,p_classification text,p_provider_name text,p_required_outcome text,p_required_for text,p_impact_if_missed text,p_management_plan text,p_owner_membership_id uuid,p_identified_date date,p_needed_by_date date) returns public.project_dependencies language plpgsql security definer set search_path='' as $$declare r public.project_dependencies%rowtype;begin if auth.uid() is null or not private.can_manage_project(p_project_id) then raise exception 'Dependency creation is not permitted.' using errcode='42501';end if;if p_identified_date>current_date then raise exception 'Identified date cannot be in the future.' using errcode='22023';end if;if not private.dependency_owner_is_eligible(p_project_id,p_owner_membership_id)then raise exception 'The selected dependency owner is not eligible.' using errcode='23514';end if;insert into public.project_dependencies(project_id,title,description,classification,provider_name,required_outcome,required_for,impact_if_missed,management_plan,owner_membership_id,identified_date,needed_by_date,created_by)values(p_project_id,p_title,p_description,p_classification,p_provider_name,p_required_outcome,p_required_for,p_impact_if_missed,p_management_plan,p_owner_membership_id,p_identified_date,p_needed_by_date,auth.uid())returning * into r;return r;end;$$;
create function public.update_project_dependency(p_dependency_id uuid,p_title text,p_description text,p_classification text,p_provider_name text,p_required_outcome text,p_required_for text,p_impact_if_missed text,p_management_plan text,p_owner_membership_id uuid,p_needed_by_date date) returns public.project_dependencies language plpgsql security definer set search_path='' as $$declare d public.project_dependencies%rowtype;r public.project_dependencies%rowtype;begin if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into d from public.project_dependencies where id=p_dependency_id for update;if d.id is null or not private.can_manage_project(d.project_id)or d.status in('Satisfied','Failed','No Longer Required')then raise exception 'Dependency update is not permitted.' using errcode='42501';end if;if not private.dependency_owner_is_eligible(d.project_id,p_owner_membership_id)then raise exception 'The selected dependency owner is not eligible.' using errcode='23514';end if;update public.project_dependencies set title=p_title,description=p_description,classification=p_classification,provider_name=p_provider_name,required_outcome=p_required_outcome,required_for=p_required_for,impact_if_missed=p_impact_if_missed,management_plan=p_management_plan,owner_membership_id=p_owner_membership_id,needed_by_date=p_needed_by_date where id=p_dependency_id returning * into r;return r;end;$$;
create function public.transition_project_dependency_active(p_dependency_id uuid,p_target_status text) returns public.project_dependencies language plpgsql security definer set search_path='' as $$declare d public.project_dependencies%rowtype;r public.project_dependencies%rowtype;begin if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into d from public.project_dependencies where id=p_dependency_id for update;if d.id is null or not private.can_manage_project(d.project_id)or d.status not in('Identified','Confirmed','In Progress','At Risk')then raise exception 'Dependency transition is not permitted.' using errcode='42501';end if;if p_target_status not in('Identified','Confirmed','In Progress','At Risk')or p_target_status=d.status then raise exception 'Unsupported dependency transition.' using errcode='22023';end if;update public.project_dependencies set status=p_target_status where id=p_dependency_id returning * into r;return r;end;$$;
create function public.conclude_project_dependency(p_dependency_id uuid,p_outcome text,p_satisfaction_evidence text,p_outcome_notes text) returns public.project_dependencies language plpgsql security definer set search_path='' as $$declare d public.project_dependencies%rowtype;r public.project_dependencies%rowtype;begin if auth.uid() is null then raise exception 'Authentication is required.' using errcode='42501';end if;select * into d from public.project_dependencies where id=p_dependency_id for update;if d.id is null or not private.can_manage_project(d.project_id)or d.status not in('Identified','Confirmed','In Progress','At Risk')then raise exception 'Dependency conclusion is not permitted.' using errcode='42501';end if;if p_outcome not in('Satisfied','Failed','No Longer Required')or nullif(btrim(p_outcome_notes),'')is null or(p_outcome='Satisfied'and nullif(btrim(p_satisfaction_evidence),'')is null)or(p_outcome<>'Satisfied'and nullif(btrim(p_satisfaction_evidence),'')is not null)then raise exception 'Required dependency outcome information is missing.' using errcode='22023';end if;update public.project_dependencies set status=p_outcome,satisfaction_evidence=case when p_outcome='Satisfied'then btrim(p_satisfaction_evidence)end,outcome_notes=btrim(p_outcome_notes),satisfied_by=case when p_outcome='Satisfied'then auth.uid()end,satisfied_at=case when p_outcome='Satisfied'then now()end,failed_by=case when p_outcome='Failed'then auth.uid()end,failed_at=case when p_outcome='Failed'then now()end,no_longer_required_by=case when p_outcome='No Longer Required'then auth.uid()end,no_longer_required_at=case when p_outcome='No Longer Required'then now()end where id=p_dependency_id returning * into r;return r;end;$$;
create function public.satisfy_project_dependency(p_dependency_id uuid,p_satisfaction_evidence text,p_outcome_notes text)returns public.project_dependencies language sql security definer set search_path='' as $$select public.conclude_project_dependency(p_dependency_id,'Satisfied',p_satisfaction_evidence,p_outcome_notes)$$;
create function public.fail_project_dependency(p_dependency_id uuid,p_outcome_notes text)returns public.project_dependencies language sql security definer set search_path='' as $$select public.conclude_project_dependency(p_dependency_id,'Failed',null,p_outcome_notes)$$;
create function public.mark_project_dependency_no_longer_required(p_dependency_id uuid,p_outcome_notes text)returns public.project_dependencies language sql security definer set search_path='' as $$select public.conclude_project_dependency(p_dependency_id,'No Longer Required',null,p_outcome_notes)$$;
create function public.get_project_dependencies(p_project_id uuid)returns table(id uuid,project_id uuid,title text,description text,classification text,provider_name text,required_outcome text,required_for text,impact_if_missed text,management_plan text,owner_membership_id uuid,owner_user_id uuid,owner_name text,owner_access_level text,owner_is_eligible boolean,identified_date date,needed_by_date date,status text,satisfaction_evidence text,outcome_notes text,satisfied_by uuid,satisfied_at timestamptz,satisfied_by_name text,failed_by uuid,failed_at timestamptz,failed_by_name text,no_longer_required_by uuid,no_longer_required_at timestamptz,no_longer_required_by_name text,created_by uuid,created_by_name text,created_at timestamptz,updated_at timestamptz)language sql stable security definer set search_path='' as $$select d.id,d.project_id,d.title,d.description,d.classification,d.provider_name,d.required_outcome,d.required_for,d.impact_if_missed,d.management_plan,d.owner_membership_id,pm.user_id,op.full_name,pm.access_level,private.dependency_owner_is_eligible(d.project_id,d.owner_membership_id),d.identified_date,d.needed_by_date,d.status,d.satisfaction_evidence,d.outcome_notes,d.satisfied_by,d.satisfied_at,sp.full_name,d.failed_by,d.failed_at,fp.full_name,d.no_longer_required_by,d.no_longer_required_at,np.full_name,d.created_by,cp.full_name,d.created_at,d.updated_at from public.project_dependencies d join public.project_members pm on pm.id=d.owner_membership_id join public.profiles op on op.id=pm.user_id join public.profiles cp on cp.id=d.created_by left join public.profiles sp on sp.id=d.satisfied_by left join public.profiles fp on fp.id=d.failed_by left join public.profiles np on np.id=d.no_longer_required_by where d.project_id=p_project_id and private.has_project_access(p_project_id)order by case when d.status in('Satisfied','Failed','No Longer Required')then 1 else 0 end,case when d.status not in('Satisfied','Failed','No Longer Required')and not private.dependency_owner_is_eligible(d.project_id,d.owner_membership_id)then 0 else 1 end,case when d.status not in('Satisfied','Failed','No Longer Required')and d.needed_by_date<current_date then 0 else 1 end,case when d.status not in('Satisfied','Failed','No Longer Required')and d.needed_by_date=current_date then 0 else 1 end,case when d.status='At Risk'then 0 else 1 end,d.needed_by_date,case when d.status in('Satisfied','Failed','No Longer Required')then coalesce(d.satisfied_at,d.failed_at,d.no_longer_required_at)end desc,d.created_at,d.id$$;
create function public.get_eligible_dependency_owners(p_project_id uuid)returns table(membership_id uuid,user_id uuid,full_name text,access_level text)language plpgsql stable security definer set search_path='' as $$begin if auth.uid()is null or not private.can_manage_project(p_project_id)then raise exception 'Dependency management is not permitted.' using errcode='42501';end if;return query select pm.id,pm.user_id,pr.full_name,pm.access_level from public.project_members pm join public.profiles pr on pr.id=pm.user_id join public.projects p on p.id=pm.project_id join public.organization_members om on om.organization_id=p.organization_id and om.user_id=pm.user_id and om.status='Active'where pm.project_id=p_project_id and pm.left_at is null and(pm.access_level='Project Member'or(pm.access_level='Project Manager'and pm.user_id=p.project_manager_id))order by pr.full_name,pm.id;end;$$;
revoke all on function private.dependency_owner_is_eligible(uuid,uuid),private.protect_project_dependency(),public.conclude_project_dependency(uuid,text,text,text)from public;
revoke all on function public.create_project_dependency(uuid,text,text,text,text,text,text,text,text,uuid,date,date),public.update_project_dependency(uuid,text,text,text,text,text,text,text,text,uuid,date),public.transition_project_dependency_active(uuid,text),public.satisfy_project_dependency(uuid,text,text),public.fail_project_dependency(uuid,text),public.mark_project_dependency_no_longer_required(uuid,text),public.get_project_dependencies(uuid),public.get_eligible_dependency_owners(uuid)from public;
grant execute on function public.create_project_dependency(uuid,text,text,text,text,text,text,text,text,uuid,date,date),public.update_project_dependency(uuid,text,text,text,text,text,text,text,text,uuid,date),public.transition_project_dependency_active(uuid,text),public.satisfy_project_dependency(uuid,text,text),public.fail_project_dependency(uuid,text),public.mark_project_dependency_no_longer_required(uuid,text),public.get_project_dependencies(uuid),public.get_eligible_dependency_owners(uuid)to authenticated;
